name: Publish to Kubernetes Staging

on:
  push:
    branches:
      - develop

jobs:
  build_push_image:
    name: Build Image and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Image build and push
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mejiandres/kai-web
          tag_with_sha: true
