name: Publish to Kubernetes Staging

on:
  push:
    branches:
      - develop

jobs:
  build_push_image:
    name: Build Image and push
    runs-on: ubuntu-latest
    steps:
      - name: Image build and push
        uses: docker/build-push-action@v1.1.0
        with:
          repository: mejiandres/kai-web
          tags: "$(echo $GITHUB_SHA | head -c7)"
